# version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: DockerFile
        container_name: laravel-app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel-mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - mysql-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root

volumes:
    mysql-data:
